SCREEN_WIDTH = 1366
SCREEN_HEIGHT = 768
COLLIDE_RATIO = 0.4
MAP_SIZE = 1
LEFT_BORDER = SCREEN_WIDTH * MAP_SIZE * -1
RIGHT_BORDER = SCREEN_WIDTH * (MAP_SIZE + 1)
TOP_BORDER = SCREEN_HEIGHT * MAP_SIZE * -1
BOTTOM_BORDER = SCREEN_HEIGHT * (MAP_SIZE + 1)